#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Aggregates output files generated by `batch_analysis.py`
"""

from pathlib import Path

import pandas as pd


DATA_DIR = Path('./data/derivatives').resolve()


def aggregate_analyses(atlas):
    """
    Aggregates analysis outputs for `atlas` into single CSV file

    Saves CSV file to atlas directory and returns concatenated dataframe

    Parameters
    ----------
    atlas : {'dk', 'dksurf'}
        Atlas for which to aggregate analysis outputs

    Returns
    -------
    analysis : pd.DataFrame
        Aggregated analysis outputs
    """

    atlas_path = DATA_DIR / atlas
    outputs = []
    for fn in atlas_path.glob('analysis_*.csv'):
        outputs.append(pd.read_csv(fn))

    concat = pd.concat(outputs, axis=0)
    concat.to_csv(atlas_path / 'analysis.csv', index=False)

    return pd.read_csv(atlas_path / 'analysis.csv')


def main():
    combo = [aggregate_analyses(atlas) for atlas in ('dk', 'dksurf')]
    pd.concat(combo, axis=0).to_csv(DATA_DIR / 'pipelines.csv.gz', index=False)


if __name__ == "__main__":
    main()
